---
- name: create polkadot group
  group:
    name: polkadot
    state: present

- name: add polkadot user
  user:
    name: polkadot
    groups: ['polkadot']
    append: yes
    shell: /bin/bash

- name: download zip binary
  get_url:
    url: 'https://github.com/neatcoin/neatcoin/releases/download/v{{ substrate_version }}/neatcoin-linux.zip'
    dest: /tmp/Neatcoin.zip
    force: true
    mode: '0700'
    owner: 'polkadot'
    group: 'polkadot'

- name: Unarchive
  unarchive:
    src: /tmp/Neatcoin.zip
    dest: /usr/local/bin
    remote_src: yes
    owner: 'polkadot'
    group: 'polkadot'

- name: create service file
  template:
    src: polkadot.service.j2
    dest: /etc/systemd/system/polkadot.service
    owner: root
    group: root
    mode: 0600

- name: restart polkadot service
  systemd:
    name: polkadot.service
    state: restarted
    daemon_reload: yes
    enabled: yes
  changed_when: false
