---
- name: Ensure base path exists
  file:
    path: '{{ base_path }}'
    state: directory
    mode: '0755'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'

- name: download polkadot binary
  get_url:
    url: "{{ polkadot_binary }}"
    dest: '/tmp/polkadex.zip'
    mode: '0700'

- name: Unarchive
  unarchive:
    src: /tmp/polkadex.zip
    dest: /usr/local/bin
    remote_src: yes
    owner: '{{ ansible_user }}'
    mode: '0755'

- name: create service file
  template:
    src: polkadex.service.j2
    dest: '/etc/systemd/system/{{ inventory_hostname }}.service'
    owner: root
    group: root
    mode: '0744'

- name: open prometheus and p2p ports
  ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
  loop:
    - '{{ port_prefix }}16'
    - '{{ port_prefix }}00'

- name: start service
  become: true
  systemd:
    name: '{{ inventory_hostname }}'
    state: restarted
    daemon_reload: yes
    enabled: yes
