- name: Pull Docker image
  docker_image:
    name: 'sora2/substrate:{{ substrate_version }}'
    source: pull

- name: create polkadot group
  group:
    name: polkadot
    state: present

- name: add polkadot user
  user:
    name: polkadot
    groups: ['polkadot', 'docker']
    append: yes
    shell: /bin/bash

- name: set folder permission if there is an alternative base_path for polkadot
  file:
    path: '{{ chain_path }}'
    state: directory
    owner: '10000'
    group: '10000'
    recurse: true
    mode: 0755
  when: chain_path is defined
  changed_when: false

- name: stop docker process
  docker_container:
    name: '{{ validator_name }}'
    state: absent

# docker run -d --restart unless-stopped --name polkachu-sora-1 -p 127.0.0.1:9933:9933 -p 127.0.0.1:9944:9944 -p 127.0.0.1:9615:9615 -v /home/polkadot/sora:/chain sora2/substrate:1.2.1 --name polkachu-sora-1 --chain main --base-path /chain --validator --rpc-methods Unsafe --rpc-cors all --execution Wasm --wasm-execution compiled --prometheus-external --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0'

- name: Start docker process
  command: "docker run -d --restart unless-stopped --name {{ validator_name }} -p 127.0.0.1:9933:9933 -p 127.0.0.1:9944:9944 -p 127.0.0.1:9615:9615 -v {{ chain_path }}:/chain sora2/substrate:{{substrate_version}} --name {{ validator_name }} --chain main --base-path /chain --validator --rpc-methods Unsafe --rpc-cors all --execution Wasm --wasm-execution compiled --prometheus-external --telemetry-url '{{ telemetry_url }} 0'"
