---
- name: create polkadot group
  group:
    name: polkadot
    state: present

- name: add polkadot user
  user:
    name: polkadot
    groups: ['polkadot']
    append: yes
    shell: /bin/bash

- name: stop polkadot service
  systemd:
    name: polkadot.service
    state: stopped
  changed_when: false

- name: download custom json
  get_url:
    url: 'https://raw.githubusercontent.com/zeitgeistpm/polkadot/battery-station-relay/node/service/res/battery-station-relay.json'
    dest: /usr/local/bin/battery-station-relay.json
    force: true
    mode: '0700'
    owner: 'polkadot'
    group: 'polkadot'

- name: download binary
  get_url:
    url: 'https://github.com/zeitgeistpm/zeitgeist/releases/download/v{{ substrate_version }}/zeitgeist_parachain'
    dest: /usr/local/bin/zeitgeist-new
    force: true
    mode: '0700'
    owner: 'polkadot'
    group: 'polkadot'

- name: substitute new binary
  shell: |
    set -o pipefail
    if [ -f /usr/local/bin/zeitgeist-new ]; then
      cp /usr/local/bin/zeitgeist-new /usr/local/bin/zeitgeist
      chown polkadot:polkadot /usr/local/bin/zeitgeist
      chmod 755 /usr/local/bin/zeitgeist
    fi
  args:
    executable: /bin/bash
  changed_when: False

- name: create service file
  template:
    src: polkadot.service.j2
    dest: /etc/systemd/system/polkadot.service
    owner: root
    group: root
    mode: 0600

- name: restart polkadot service
  systemd:
    name: polkadot.service
    state: restarted
    daemon_reload: yes
    enabled: yes
  changed_when: false
