---
- name: install dependency
  apt:
    name: '{{item}}'
    state: present
    update_cache: yes
  loop:
    - python3-pip
    - python3-setuptools

- name: add GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ubuntu_version | default('hirsute') }} stable
    state: present

- name: install docker
  apt:
    name: '{{item}}'
    state: latest
    update_cache: yes
  loop:
    - docker-ce

- name: installing docker SDK
  command: 'pip3 install docker'

- name: add ubuntu user to docker group
  user:
    name: ubuntu
    groups: ['docker']
    append: yes
